<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(){
  Schema::create('categories',function(Blueprint $t){$t->id();$t->foreignId('parent_id')->nullable()->constrained('categories')->nullOnDelete();$t->string('name');$t->string('slug')->unique();$t->string('tagline')->nullable();$t->string('heading')->nullable();$t->text('description')->nullable();$t->string('image')->nullable();$t->string('banner_image')->nullable();$t->string('meta_title')->nullable();$t->text('meta_description')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->boolean('show_in_menu')->default(true);$t->timestamps();$t->index(['parent_id','is_active','sort_order']);});
  Schema::create('products',function(Blueprint $t){$t->id();$t->foreignId('category_id')->constrained()->restrictOnDelete();$t->foreignId('subcategory_id')->nullable()->constrained('categories')->nullOnDelete();$t->string('name');$t->string('slug')->unique();$t->string('sku')->unique();$t->text('short_description')->nullable();$t->longText('description')->nullable();$t->string('material')->nullable();$t->decimal('price',12,2);$t->decimal('compare_price',12,2)->nullable();$t->decimal('cost_price',12,2)->nullable();$t->unsignedInteger('stock')->default(0);$t->unsignedInteger('low_stock_threshold')->default(5);$t->decimal('weight',8,2)->nullable();$t->json('colors')->nullable();$t->json('sizes')->nullable();$t->json('tags')->nullable();$t->decimal('rating',3,2)->default(0);$t->unsignedInteger('review_count')->default(0);$t->boolean('is_active')->default(true);$t->boolean('is_featured')->default(false);$t->boolean('is_new')->default(false);$t->boolean('is_bestseller')->default(false);$t->boolean('is_limited')->default(false);$t->string('meta_title')->nullable();$t->text('meta_description')->nullable();$t->string('canonical_url')->nullable();$t->timestamps();$t->softDeletes();$t->index(['category_id','is_active','is_featured']);$t->index(['price','stock']);});
  Schema::create('product_images',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('path');$t->string('alt_text')->nullable();$t->unsignedTinyInteger('sort_order')->default(0);$t->boolean('is_primary')->default(false);$t->timestamps();$t->unique(['product_id','sort_order']);});
  Schema::create('product_variants',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('sku')->unique();$t->string('color')->nullable();$t->string('size')->nullable();$t->decimal('price',12,2)->nullable();$t->unsignedInteger('stock')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('collections',function(Blueprint $t){$t->id();$t->string('title');$t->string('slug')->unique();$t->string('tagline')->nullable();$t->text('description')->nullable();$t->string('image')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('collection_product',function(Blueprint $t){$t->foreignId('collection_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('sort_order')->default(0);$t->primary(['collection_id','product_id']);});
 }
 public function down(){Schema::dropIfExists('collection_product');Schema::dropIfExists('collections');Schema::dropIfExists('product_variants');Schema::dropIfExists('product_images');Schema::dropIfExists('products');Schema::dropIfExists('categories');}
};
