<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(){
  Schema::create('addresses',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->cascadeOnDelete();$t->string('label')->default('Home');$t->string('name');$t->string('phone',30);$t->string('email')->nullable();$t->string('address_line_1');$t->string('address_line_2')->nullable();$t->string('area')->nullable();$t->string('city');$t->string('district');$t->string('postal_code',20)->nullable();$t->string('country',2)->default('BD');$t->boolean('is_default')->default(false);$t->timestamps();});
  Schema::create('coupons',function(Blueprint $t){$t->id();$t->string('code')->unique();$t->enum('type',['fixed','percent']);$t->decimal('value',12,2);$t->decimal('minimum_order',12,2)->default(0);$t->decimal('maximum_discount',12,2)->nullable();$t->unsignedInteger('usage_limit')->nullable();$t->unsignedInteger('used_count')->default(0);$t->timestamp('starts_at')->nullable();$t->timestamp('expires_at')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('orders',function(Blueprint $t){$t->id();$t->string('order_number')->unique();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('coupon_id')->nullable()->constrained()->nullOnDelete();$t->enum('status',['pending','confirmed','processing','shipped','delivered','cancelled','refunded'])->default('pending')->index();$t->enum('payment_status',['unpaid','pending','paid','failed','refunded'])->default('unpaid')->index();$t->string('payment_method')->default('cod');$t->string('transaction_id')->nullable()->index();$t->decimal('subtotal',12,2);$t->decimal('discount',12,2)->default(0);$t->decimal('shipping',12,2)->default(0);$t->decimal('tax',12,2)->default(0);$t->decimal('total',12,2);$t->json('shipping_address');$t->json('billing_address')->nullable();$t->text('customer_note')->nullable();$t->text('admin_note')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamp('delivered_at')->nullable();$t->timestamp('stock_restored_at')->nullable();$t->timestamps();});
  Schema::create('order_items',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('product_variant_id')->nullable()->constrained()->nullOnDelete();$t->string('product_name');$t->string('sku');$t->string('image')->nullable();$t->string('color')->nullable();$t->string('size')->nullable();$t->decimal('unit_price',12,2);$t->unsignedInteger('quantity');$t->decimal('total',12,2);$t->timestamps();});
  Schema::create('order_status_histories',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('status');$t->text('note')->nullable();$t->timestamps();});
  Schema::create('wishlists',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->timestamps();$t->unique(['user_id','product_id']);});
  Schema::create('reviews',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->foreignId('order_id')->nullable()->constrained()->nullOnDelete();$t->unsignedTinyInteger('rating');$t->string('title')->nullable();$t->text('comment');$t->enum('status',['pending','approved','rejected'])->default('pending');$t->boolean('is_verified_purchase')->default(false);$t->timestamps();$t->unique(['user_id','product_id','order_id']);});
 }
 public function down(){Schema::dropIfExists('reviews');Schema::dropIfExists('wishlists');Schema::dropIfExists('order_status_histories');Schema::dropIfExists('order_items');Schema::dropIfExists('orders');Schema::dropIfExists('coupons');Schema::dropIfExists('addresses');}
};
