@extends('layouts.store')
@section('title','SARAI — Authentic Bangladeshi Craft, Handloom & Lifestyle')
@section('description','Discover curated Jamdani, Nakshi Kantha, Shital Pati, handloom fashion, pottery, jewellery, jute, cane and home décor made by Bangladeshi artisans.')
@section('content')
<section class="hero" aria-label="Featured collections">
 @forelse($banners as $i=>$banner)<article class="hero-slide {{ $i===0?'is-active':'' }}"><picture>@if($banner->mobile_image)<source media="(max-width:680px)" srcset="{{ asset($banner->mobile_image) }}">@endif<img src="{{ asset($banner->image) }}" alt="{{ $banner->title }}" fetchpriority="{{ $i===0?'high':'low' }}"></picture><div class="hero-copy"><p class="eyebrow !text-copper-300 mb-4">{{ $banner->eyebrow }}</p><h1 class="display">{{ $banner->title }}</h1><h2 class="text-2xl md:text-3xl mt-4 text-white">{{ $banner->subtitle }}</h2><p class="max-w-xl mt-5 text-white/75">{{ $banner->description }}</p><div class="flex flex-wrap gap-3 mt-8"><a class="btn btn-light" href="{{ url($banner->button_url?:'/new-arrivals') }}">{{ $banner->button_text?:'Explore' }} <i class="fa-solid fa-arrow-right"></i></a></div></div></article>@empty<article class="hero-slide is-active"><img src="{{ asset('images/hero/hero-festive.webp') }}" alt="SARAI festive collection"><div class="hero-copy"><p class="eyebrow text-white">Bangladeshi Craft</p><h1 class="display">Tradition, gathered.</h1></div></article>@endforelse
 <div class="hero-dots">@foreach($banners as $i=>$banner)<button class="hero-dot {{ $i===0?'is-active':'' }}" aria-label="Show {{ $banner->title }}"></button>@endforeach</div>
</section>
<section class="section"><div class="wrap"><div class="text-center max-w-2xl mx-auto mb-12 reveal"><p class="eyebrow">From across Bangladesh</p><h2 class="heading mt-3">Made by hand. Chosen with care.</h2><p class="muted mt-4">A modern gathering place for the work of weavers, potters, embroiderers, rural families and independent workshops.</p></div><div class="category-grid">@foreach($navCategories->take(8) as $category)<a class="category-tile" href="{{ route('categories.show',$category) }}"><img src="{{ asset($category->image) }}" loading="lazy" alt="{{ $category->name }} — {{ $category->tagline }}"><div class="category-caption"><p class="eyebrow !text-white/70">{{ $category->tagline }}</p><h3 class="text-3xl mt-2">{{ $category->name }}</h3><span class="text-[10px] uppercase tracking-widest2">Discover <i class="fa-solid fa-arrow-right ml-2"></i></span></div></a>@endforeach</div></div></section>
<section class="section bg-white"><div class="wrap"><div class="flex items-end justify-between mb-10 reveal"><div><p class="eyebrow">Just arrived</p><h2 class="heading mt-2">New to the floor</h2></div><a class="hidden md:block text-xs uppercase tracking-widest2" href="{{ route('new-arrivals') }}">View all <i class="fa-solid fa-arrow-right ml-2"></i></a></div><div class="product-grid">@foreach($newArrivals as $product)<x-product-card :product="$product"/>@endforeach</div></div></section>
<section class="section"><div class="wrap"><div class="text-center mb-10 reveal"><p class="eyebrow">Stories in cloth and clay</p><h2 class="heading mt-2">Curated collections</h2></div><div class="collection-grid">@foreach($collections as $collection)<a class="collection-card reveal" href="{{ route('collections.show',$collection) }}"><img src="{{ asset($collection->image) }}" loading="lazy" alt="{{ $collection->title }}"><div class="category-caption"><p class="eyebrow !text-white/70">{{ $collection->tagline }}</p><h3 class="text-4xl mt-2">{{ $collection->title }}</h3></div></a>@endforeach</div></div></section>
<section class="section bg-[#173d32] text-white"><div class="wrap grid md:grid-cols-2 gap-12 items-center"><div class="reveal"><img src="{{ asset('images/editorial/craft.webp') }}" loading="lazy" alt="Bangladeshi artisan craft process"></div><div class="reveal"><p class="eyebrow !text-white/60">Maker → creation → SARAI → you</p><h2 class="heading !text-white mt-3">The maker stays in the story.</h2><p class="text-white/70 mt-6 max-w-lg">We do not erase where a piece comes from. Regional technique, material, time and maker remain part of how each object is presented and valued.</p><a href="{{ route('pages.show','about') }}" class="btn btn-light mt-8">Our approach <i class="fa-solid fa-arrow-right"></i></a></div></div></section>
<section class="section"><div class="wrap"><div class="flex items-end justify-between mb-10"><div><p class="eyebrow">The journal</p><h2 class="heading mt-2">Notes on making</h2></div><a href="{{ route('journal') }}" class="text-xs uppercase tracking-widest2">Read all</a></div><div class="grid md:grid-cols-3 gap-8">@foreach($posts as $post)<article class="reveal"><a href="{{ route('journal.show',$post) }}"><div class="aspect-[4/3] overflow-hidden"><img class="w-full h-full object-cover transition duration-700 hover:scale-105" src="{{ asset($post->image) }}" alt="{{ $post->title }}" loading="lazy"></div><p class="eyebrow mt-5">{{ $post->category }} · {{ $post->published_at->format('d M Y') }}</p><h3 class="text-3xl mt-2">{{ $post->title }}</h3><p class="muted mt-3">{{ $post->excerpt }}</p></a></article>@endforeach</div></div></section>
@endsection
