@extends('layouts.store')
@section('title',$product->meta_title?:$product->name.' | SARAI') @section('description',$product->meta_description?:$product->short_description) @section('canonical',$product->canonical_url?:route('products.show',$product)) @section('og_type','product') @section('og_image',asset($product->primaryImage->path))
@push('schema')<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'Product','name'=>$product->name,'image'=>$product->images->map(fn($i)=>asset($i->path))->all(),'description'=>$product->short_description,'sku'=>$product->sku,'brand'=>['@type'=>'Brand','name'=>'SARAI'],'offers'=>['@type'=>'Offer','url'=>route('products.show',$product),'priceCurrency'=>'BDT','price'=>(float)$product->price,'availability'=>$product->stock>0?'https://schema.org/InStock':'https://schema.org/OutOfStock'],'aggregateRating'=>$product->review_count?['@type'=>'AggregateRating','ratingValue'=>(float)$product->rating,'reviewCount'=>$product->review_count]:null],JSON_UNESCAPED_SLASHES) !!}</script>@endpush
@section('content')
<div class="wrap py-8"><nav class="text-xs muted mb-8"><a href="{{ route('home') }}">Home</a> / <a href="{{ route('categories.show',$product->category) }}">{{ $product->category->name }}</a> / <span>{{ $product->name }}</span></nav>
<div class="product-detail"><div><div class="gallery">@foreach($product->images as $i=>$image)<img @if($i===0)data-main-image @endif src="{{ asset($image->path) }}" alt="{{ $image->alt_text?:$product->name }}" width="800" height="1000" {{ $i?'loading=lazy':'fetchpriority=high' }}>@endforeach</div><div class="mobile-thumbs">@foreach($product->images as $image)<button type="button" data-thumb="{{ asset($image->path) }}"><img src="{{ asset($image->path) }}" alt="View {{ $product->name }}"></button>@endforeach</div></div>
<aside class="product-summary"><p class="eyebrow">{{ $product->category->name }} · {{ $product->material }}</p><h1 class="heading mt-2 !text-[clamp(2.4rem,4vw,4rem)]">{{ $product->name }}</h1><div class="flex items-center gap-3 mt-4"><p class="text-lg"><strong class="{{ $product->compare_price?'price-sale':'' }}">৳{{ number_format($product->price) }}</strong>@if($product->compare_price)<span class="price-old">৳{{ number_format($product->compare_price) }}</span>@endif</p>@if($product->review_count)<span class="text-xs"><i class="fa-solid fa-star text-copper-500"></i> {{ $product->rating }} ({{ $product->review_count }})</span>@endif</div><p class="muted mt-6">{{ $product->short_description }}</p>
<form action="{{ route('cart.store',$product) }}" method="post" class="mt-8">@csrf
 @if(count($product->colors??[]))<fieldset><legend class="label">Colour</legend><div class="swatches">@foreach($product->colors as $i=>$color)<label title="{{ $color['name'] }}" class="swatch cursor-pointer" style="background:{{ $color['hex']??'#ccc' }}"><input class="sr-only" type="radio" name="color" value="{{ $color['name'] }}" @checked($i===0)></label>@endforeach</div></fieldset>@endif
 @if(count($product->sizes??[]))<fieldset class="mt-6"><legend class="label">Size <a class="float-right normal-case tracking-normal underline" href="{{ route('pages.show','size-guide') }}">Size guide</a></legend><div class="flex flex-wrap gap-2">@foreach($product->sizes as $i=>$size)<label class="option relative cursor-pointer"><input type="radio" name="size" value="{{ $size }}" @checked($i===0)><span>{{ $size }}</span></label>@endforeach</div></fieldset>@endif
 <div class="flex gap-3 mt-7"><div class="qty" data-qty><button type="button" data-minus aria-label="Decrease">−</button><input class="text-center" name="quantity" value="1" inputmode="numeric"><button type="button" data-plus aria-label="Increase">+</button></div><button class="btn btn-dark flex-1" @disabled($product->stock<1)>{{ $product->stock?'Add to bag':'Sold out' }}</button></div>
</form>
<div class="mt-8"><details class="accordion" open><summary>Description <i class="fa-solid fa-plus text-xs"></i></summary><div>{!! nl2br(e($product->description)) !!}</div></details><details class="accordion"><summary>Materials & care <i class="fa-solid fa-plus text-xs"></i></summary><div>{{ $product->material }}. Handcrafted pieces may show small variations. Follow the care label supplied with your item.</div></details><details class="accordion"><summary>Delivery & returns <i class="fa-solid fa-plus text-xs"></i></summary><div>Delivery across Bangladesh in 2–5 working days. Eligible unused items may be returned within 7 days.</div></details></div><p class="text-xs muted mt-5">SKU: {{ $product->sku }} · {{ $product->stock }} available</p></aside></div></div>
@if($product->approvedReviews->count())<section class="section border-t hairline"><div class="wrap"><p class="eyebrow">What customers say</p><h2 class="heading mt-2">Reviews</h2><div class="grid md:grid-cols-3 gap-6 mt-10">@foreach($product->approvedReviews->take(6) as $review)<blockquote class="card p-6"><p class="text-copper-500">{{ str_repeat('★',$review->rating) }}{{ str_repeat('☆',5-$review->rating) }}</p><p class="mt-4">“{{ $review->comment }}”</p><footer class="eyebrow mt-5">{{ $review->user->name }} @if($review->is_verified_purchase)· Verified purchase @endif</footer></blockquote>@endforeach</div></div></section>@endif
<section class="section bg-white"><div class="wrap"><p class="eyebrow">You may also like</p><h2 class="heading mt-2 mb-10">Related pieces</h2><div class="product-grid">@foreach($related as $item)<x-product-card :product="$item"/>@endforeach</div></div></section>
@endsection
